//
// Created by Isaac on 20/11/2020.
//

#ifndef STRINGSEARCHCOMPARISON_KNUTHMORRISPRATT_H
#define STRINGSEARCHCOMPARISON_KNUTHMORRISPRATT_H


class KnuthMorrisPratt {

};


#endif //STRINGSEARCHCOMPARISON_KNUTHMORRISPRATT_H
